-- Reference data only: user-specific programs and session data are created after login.
insert into public.muscle_groups (name_ar, name_en) values
('الصدر','Chest'),('الظهر','Back'),('الأكتاف','Shoulders'),('البايسبس','Biceps'),('الترايسبس','Triceps'),('البطن','Core'),('الأرجل','Legs'),('الألوية','Glutes'),('السمانة','Calves'),('كامل الجسم','Full Body'),('الكارديو','Cardio') on conflict do nothing;
insert into public.equipment (name_ar, name_en) values
('وزن الجسم','Bodyweight'),('دمبل','Dumbbell'),('بار','Barbell'),('كيبل','Cable'),('أجهزة','Machine'),('كيتل بيل','Kettlebell'),('مقاومة مطاطية','Resistance band'),('جهاز كارديو','Cardio machine'),('معدات أخرى','Other') on conflict do nothing;
insert into public.achievements (code,title_ar,description_ar,category,points,badge_icon,rule_key) values
('first_workout','أول تمرين','أكملت أول جلسة تدريبية.','training',100,'🏁','workouts_1'),('workouts_5','خمسة تمارين','أكملت خمس جلسات.','training',150,'🔥','workouts_5'),('workouts_10','عشرة تمارين','أكملت عشر جلسات.','training',250,'⚡','workouts_10'),('week_streak','أسبوع التزام','حافظت على عاداتك لأسبوع.','consistency',300,'🗓️','streak_7'),('personal_record','رقم شخصي جديد','حققت رقمًا شخصيًا جديدًا.','performance',200,'🏆','pr_1'),('water_goal','بطل الترطيب','حققت هدف الماء اليومي.','nutrition',75,'💧','water_goal'),('protein_goal','هدف البروتين','حققت هدف البروتين اليومي.','nutrition',75,'🥩','protein_goal') on conflict do nothing;
insert into public.challenges (title_ar,description_ar,cadence,target_value,rule_key) values
('أكمل تمرين اليوم','أكمل جلسة واحدة اليوم.','daily',1,'complete_workout'),('ثلاث جلسات','أكمل ثلاث جلسات هذا الأسبوع.','weekly',3,'weekly_sessions'),('ترطيب منتظم','حقق هدف الماء خمسة أيام.','weekly',5,'water_goal_days') on conflict do nothing;

insert into public.training_activities (code,category,name_ar,name_en) values
('walking','cardio','مشي','Walking'),('running','cardio','جري','Running'),('cycling','cardio','دراجة','Cycling'),('elliptical','cardio','جهاز بيضاوي','Elliptical'),('stair-climber','cardio','Stair Climber','Stair Climber'),('rowing','cardio','جهاز تجديف','Rowing Machine'),('jump-rope','cardio','نط حبل','Jump Rope'),('swimming','cardio','سباحة','Swimming'),('free-cardio','cardio','كارديو حر','Free Cardio'),
('hiit','fitness','HIIT','HIIT'),('circuit','fitness','Circuit','Circuit'),('bodyweight','fitness','Bodyweight','Bodyweight'),('core','fitness','Core','Core'),('stretching','fitness','Stretching','Stretching'),('flexibility','fitness','Flexibility','Flexibility'),('agility','fitness','Agility','Agility'),('endurance','fitness','Endurance','Endurance'),('fitness-free','fitness','Fitness Free','Fitness Free') on conflict do nothing;
insert into public.motivational_messages (body_ar,context) values
('كل مجموعة تنهيها اليوم تقرّبك من نسختك الأقوى.','workout'),('الاستمرارية أقوى من الحماس المؤقت.','general'),('سجّل الأداء الآن لتكسب وضوحًا أفضل غدًا.','workout'),('أعط جسمك وقوده، وامنح هدفك فرصته.','nutrition') on conflict do nothing;

-- Seed catalogue: 30 removable starter exercises. user_id = null marks catalogue data.
insert into public.exercises (user_id,name_ar,name_en,primary_muscle_id,difficulty,movement_type) select null, v.name_ar, v.name_en, m.id, v.difficulty, v.movement from (values
('سكوات بالبار','Barbell Back Squat','الأرجل','intermediate','push'),('سكوات أمامي','Front Squat','الأرجل','advanced','push'),('ضغط الأرجل','Leg Press','الأرجل','beginner','push'),('رفعة رومانية','Romanian Deadlift','الأرجل','intermediate','pull'),('اندفاع دمبل','Dumbbell Lunge','الأرجل','beginner','push'),('رفع سمانة واقف','Standing Calf Raise','السمانة','beginner','isolation'),('ضغط صدر بالبار','Barbell Bench Press','الصدر','intermediate','push'),('ضغط دمبل مائل','Incline Dumbbell Press','الصدر','intermediate','push'),('تفتيح كيبل','Cable Fly','الصدر','beginner','isolation'),('ضغط أرضي','Push Up','الصدر','beginner','push'),('تجديف بار منحني','Bent Over Row','الظهر','intermediate','pull'),('سحب علوي','Lat Pulldown','الظهر','beginner','pull'),('تجديف كيبل جالس','Seated Cable Row','الظهر','beginner','pull'),('عقلة','Pull Up','الظهر','advanced','pull'),('ضغط كتف واقف','Overhead Press','الأكتاف','intermediate','push'),('رفرفة جانبية','Lateral Raise','الأكتاف','beginner','isolation'),('رفرفة خلفية','Reverse Fly','الأكتاف','beginner','isolation'),('بايسبس دمبل','Dumbbell Curl','البايسبس','beginner','isolation'),('بايسبس بار','Barbell Curl','البايسبس','intermediate','isolation'),('هامر كيرل','Hammer Curl','البايسبس','beginner','isolation'),('دفع ترايسبس كيبل','Cable Triceps Pushdown','الترايسبس','beginner','isolation'),('سكَل كراشر','Skull Crusher','الترايسبس','intermediate','isolation'),('بلانك','Plank','البطن','beginner','isometric'),('كرنش كيبل','Cable Crunch','البطن','beginner','isolation'),('رفع الرجلين','Hanging Leg Raise','البطن','intermediate','isolation'),('هيب ثرست','Hip Thrust','الألوية','intermediate','push'),('كيتل بيل سوينغ','Kettlebell Swing','كامل الجسم','intermediate','hinge'),('بيربي','Burpee','كامل الجسم','intermediate','conditioning'),('مشي سريع','Brisk Walking','الكارديو','beginner','cardio'),('جهاز التجديف','Rowing Machine','الكارديو','beginner','cardio')) as v(name_ar,name_en,muscle,difficulty,movement) join public.muscle_groups m on m.name_ar = v.muscle on conflict do nothing;
