"use client";
import { Plus, StickyNote } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Modal } from "@/components/ui/modal";
const initialNotes = [{ title: "السكوات", category: "تدريب", content: "حافظ على ثبات الركبتين في آخر مجموعتين.", date: "اليوم" }, { title: "وجبة ما قبل التمرين", category: "تغذية", content: "الموز والقهوة أعطياني طاقة متوازنة.", date: "أمس" }];
export default function NotesPage() { const [notes, setNotes] = useState(initialNotes); const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); return <><div className="page-intro"><div><p className="eyebrow">سجل شخصي</p><h2>الملاحظات</h2><p>اربط ملاحظات التدريب والتغذية والقياسات بسياقها.</p></div><Button onClick={() => setOpen(true)}><Plus size={17} /> ملاحظة جديدة</Button></div><div className="exercise-grid">{notes.map((note, index) => <Card className="exercise-card" key={`${note.title}-${index}`}><StickyNote color="var(--orange)" size={22} /><div className="exercise-card__top" style={{ marginTop: ".7rem" }}><h3>{note.title}</h3><span className="pill">{note.category}</span></div><p style={{ direction: "rtl", textAlign: "right", marginTop: ".55rem" }}>{note.content}</p><div className="exercise-footer"><span>{note.date}</span><Button variant="ghost" size="sm">تعديل</Button></div></Card>)}</div><Modal open={open} title="ملاحظة جديدة" onClose={() => setOpen(false)}><label>العنوان<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label style={{ marginTop: ".8rem" }}>المحتوى<textarea rows={4} value={content} onChange={(event) => setContent(event.target.value)} /></label><div className="form-actions"><Button variant="secondary" onClick={() => setOpen(false)}>إلغاء</Button><Button onClick={() => { if (title && content) { setNotes([{ title, content, category: "عامة", date: "الآن" }, ...notes]); setOpen(false); setTitle(""); setContent(""); } }}>حفظ</Button></div></Modal></>;
}
