"use client";

import { ArrowLeft, Dumbbell, Flame, Timer, Weight } from "lucide-react";
import Link from "next/link";
import { DashboardRealtime } from "@/components/dashboard/dashboard-realtime";
import { Card, SectionHeading } from "@/components/ui/card";
import { MetricCard } from "@/components/ui/metric-card";
import { ProgressBar } from "@/components/ui/progress";
import { formatDate, percent } from "@/lib/fitness";
import type { DashboardData } from "@/types/fitness";

const week = [{ day: "س", value: 70, done: true }, { day: "ح", value: 44, done: true }, { day: "إ", value: 24, done: false }, { day: "ث", value: 76, done: true }, { day: "أ", value: 20, done: false }, { day: "خ", value: 32, done: false }, { day: "ج", value: 8, done: false }];

export function DashboardView({ data }: { data: DashboardData }) {
  const adherence = percent(data.weekly.completed, data.weekly.planned);
  return <><DashboardRealtime /><section className="dashboard-hero"><div className="hero-copy"><p className="eyebrow">{formatDate(data.today.date)}</p><h2>أهلًا {data.profile.firstName}،<br />جاهز ليوم أقوى؟</h2><p>{data.motivation}</p><div className="hero-actions"><Link href="/workouts/start" className="button button--primary button--lg"><Dumbbell size={19} /> بدء تمرين اليوم</Link><Link href="/workouts" className="button button--secondary button--lg">عرض البرنامج <ArrowLeft size={17} /></Link></div></div><div className="hero-meta"><div className="mini-stat"><strong>{data.today.estimatedMinutes}</strong><span>دقيقة متوقعة</span></div><div className="mini-stat"><strong>{data.today.workoutName}</strong><span>{data.today.workoutFocus}</span></div></div></section><div className="metrics-grid"><MetricCard icon={Dumbbell} label="تمارين الأسبوع" value={`${data.weekly.completed}/${data.weekly.planned}`} change={`${adherence}% التزام`} /><MetricCard icon={Timer} tone="blue" label="وقت التدريب" value={data.weekly.minutes} suffix="دقيقة" change="يُحدّث تلقائيًا" /><MetricCard icon={Flame} tone="orange" label="سلسلة الالتزام" value={data.weekly.currentStreak} suffix="أيام" change={`الأطول: ${data.weekly.longestStreak} يومًا`} /><MetricCard icon={Weight} label="الوزن الحالي" value={data.profile.currentWeight} suffix="كجم" change="آخر قياس محفوظ" /></div><div className="dashboard-grid"><div><Card className="daily-goals"><SectionHeading eyebrow="اليوم" title="أهدافك اليومية" action={<Link href="/nutrition">التفاصيل</Link>} /><div className="goals-list"><ProgressBar label="السعرات" value={data.consumed.calories} goal={data.goals.calories} detail={`${data.consumed.calories} / ${data.goals.calories} سعرة`} tone="orange" /><ProgressBar label="البروتين" value={data.consumed.protein} goal={data.goals.protein} detail={`${data.consumed.protein} / ${data.goals.protein} غ`} /><ProgressBar label="الماء" value={data.consumed.water} goal={data.goals.water} detail={`${(data.consumed.water / 1000).toFixed(2)} / ${data.goals.water / 1000} لتر`} tone="blue" /></div></Card><Card className="achievement-card"><span className="achievement-badge">{data.latestAchievement.icon}</span><div><p className="eyebrow">آخر إنجاز</p><h3>{data.latestAchievement.title}</h3><p>{data.latestAchievement.description}</p></div></Card></div><Card className="week-summary"><SectionHeading eyebrow="أداؤك" title="ملخص الأسبوع" action={<Link href="/reports">عرض التقرير</Link>} /><div className="week-chart">{week.map((item) => <div key={item.day} className={item.done ? "bar-column bar-column--done" : "bar-column"}><span style={{ height: `${item.value + 20}px` }} /><b>{item.day}</b></div>)}</div><ProgressBar label="الالتزام الأسبوعي" value={data.weekly.completed} goal={data.weekly.planned} detail={`${adherence}%`} /></Card></div></>;
}
