"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";

const goals = ["خسارة الدهون", "بناء العضلات", "تحسين اللياقة", "زيادة القوة", "الحفاظ على الوزن", "تحسين الصحة العامة"];
export function OnboardingFlow() {
  const [step, setStep] = useState(1); const router = useRouter(); const [values, setValues] = useState({ name: "", height: "", weight: "", target: "", goal: "بناء العضلات", days: "3" }); const update = (key: keyof typeof values, value: string) => setValues({ ...values, [key]: value });
  return <main className="onboarding"><header className="onboarding__header"><p className="eyebrow">إعداد الحساب · {step}/3</p><h1>لنضبط FA FITNESS على أهدافك</h1><p>يمكنك تعديل كل شيء لاحقًا من الحساب.</p></header><div className="onboarding-stepper" aria-label={`الخطوة ${step} من 3`}>{[1,2,3].map((item) => <span key={item} className={item <= step ? "active" : ""} />)}</div><section className="card onboarding-card">{step === 1 ? <><h2>عنّك</h2><div className="form-grid"><label>الاسم الأول<input value={values.name} onChange={(event) => update("name", event.target.value)} placeholder="مثال: فيصل" /></label><label>الطول (سم)<input inputMode="numeric" value={values.height} onChange={(event) => update("height", event.target.value)} /></label><label>الوزن الحالي (كجم)<input inputMode="decimal" value={values.weight} onChange={(event) => update("weight", event.target.value)} /></label><label>الوزن المستهدف (كجم)<input inputMode="decimal" value={values.target} onChange={(event) => update("target", event.target.value)} /></label></div></> : null}{step === 2 ? <><h2>ما هدفك الآن؟</h2><div className="chip-grid">{goals.map((goal) => <button key={goal} className={values.goal === goal ? "choice-chip choice-chip--selected" : "choice-chip"} onClick={() => update("goal", goal)}>{goal}</button>)}</div></> : null}{step === 3 ? <><h2>برنامجك الأسبوعي</h2><div className="form-grid"><label>أيام التدريب أسبوعيًا<select value={values.days} onChange={(event) => update("days", event.target.value)}>{[2,3,4,5,6].map((day) => <option key={day} value={day}>{day} أيام</option>)}</select></label><label>مكان التدريب<select><option>نادي رياضي</option><option>المنزل</option><option>كلاهما</option></select></label><label>الوحدة المفضلة<select><option>كجم</option><option>رطل</option></select></label><label>هدف الماء<select><option>3 لترات يوميًا</option><option>2.5 لتر يوميًا</option><option>4 لترات يوميًا</option></select></label></div></> : null}<footer className="onboarding-footer">{step > 1 ? <Button variant="secondary" onClick={() => setStep((value) => value - 1)}>السابق</Button> : <span />}{step < 3 ? <Button onClick={() => setStep((value) => value + 1)}>التالي</Button> : <Button onClick={() => router.push("/dashboard")}>بدء الرحلة</Button>}</footer></section></main>;
}
